name: Automatic update project documentation

on:
  push:
    branches:
      - main
env:
  extensions: json
  defaultPHPVersion: '8.0.3'
  
jobs:
#  generate_docs:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#      - name: Setup PHP
#        uses: shivammathur/setup-php@master
#        with:
#          php-version: ${{ env.defaultPHPVersion }}
#          extensions: ${{ env.extensions }}
#          ini-values: memory_limit=2G, display_errors=On, error_reporting=-1
#          tools: pecl
#
#      - name: Install Composer dependencies
#        run: |
#          composer install --no-progress --prefer-dist --optimize-autoloader
#      - name: Generate Documentatio
#        run: |
#          mkdir bin
#          cd bin/
#          wget https://phpdoc.org/phpDocumentor.phar
#          cd ..
#          mkdir -p ./docs/documentation
#          php bin/phpDocumentor.phar run -d ./ -t ./docs/documentation --ignore vendor/ --setting="guides.enabled=true" --force -v
#          rm -rf tmp/
  update_wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkouting project code...
        uses: actions/checkout@v2
      - name: Updating wiki...
        uses: impresscms-dev/phpdocs-wiki-update-action@v1.0.0
        with:
          wiki_github_update_token: ${{ secrets.WIKI_GITHUB_UPDATE_TOKEN }}
          wiki_github_update_user: ${{ secrets.WIKI_GITHUB_UPDATE_USER }}
          engine: evert/phpdoc-md
