name: Automatic update project documentation

on:
  push:
    branches:
      - main
env:
  extensions: json
  defaultPHPVersion: '8.0'
  
jobs:
  generate_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ env.defaultPHPVersion }}
          extensions: ${{ env.extensions }}
          ini-values: memory_limit=2G, display_errors=On, error_reporting=-1
          tools: pecl

      - name: Install Composer dependencies
        run: |
          composer install --no-progress --prefer-dist --optimize-autoloader          
      - name: Generate Documentation
        if: success()
        run: |
          mkdir bin
          cd bin/
          wget https://phpdoc.org/phpDocumentor.phar 
          cp phpDocumentor.phar phpDoc
          chmod +x phpDoc
          cd ..
          mkdir -p ./docs/documentation
          ./bin/phpDoc run -d ./ -t ./docs/documentation --setting="guides.enabled=true" --force -v
          rm -rf tmp/

